// This file was autogenerated by closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../simple-tree-grid/defaultBranchToggler.js', ['bwoester.simpleTreeGrid.DefaultBranchToggler'], []);
goog.addDependency('../../../simple-tree-grid/rowData.js', ['bwoester.simpleTreeGrid.RowData'], ['bwoester.Ternary']);
goog.addDependency('../../../simple-tree-grid/ternary.js', ['bwoester.Ternary'], []);
goog.addDependency('../../../simple-tree-grid/treeNode.js', ['bwoester.TreeNode'], ['goog.structs.TreeNode']);
