// This file was autogenerated by closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../simple-tree-grid/branchDecorator.js', ['bwoester.simpleTreeGrid.BranchDecorator'], ['bwoester.Ternary', 'bwoester.simpleTreeGrid.IComponent']);
goog.addDependency('../../../simple-tree-grid/branchToggler.js', ['bwoester.simpleTreeGrid.BranchToggler'], ['bwoester.Ternary', 'bwoester.simpleTreeGrid.IComponent']);
goog.addDependency('../../../simple-tree-grid/factory.js', ['bwoester.Factory'], []);
goog.addDependency('../../../simple-tree-grid/interfaces.js', ['bwoester.simpleTreeGrid.IComponent'], []);
goog.addDependency('../../../simple-tree-grid/rowData.js', ['bwoester.simpleTreeGrid.RowData'], ['bwoester.Ternary']);
goog.addDependency('../../../simple-tree-grid/ternary.js', ['bwoester.Ternary'], []);
goog.addDependency('../../../simple-tree-grid/treeNode.js', ['bwoester.TreeNode'], ['goog.structs.TreeNode']);
