// This file was autogenerated by closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../simple-tree-grid/treeNode.js', ['bwoester.TreeNode'], ['goog.structs.TreeNode']);
